### ISSUE TITLE
Makes no sense and made things worse! and KSP UNPLAYABLE!

### ISSUE THREAD

**Issue by neil501** [net-lisias-ksp/ModuleManager#7]
I downloaded and installed this and now ksp dont work it says i have other copies of mod manager but this is the only one ive downloaded. Looks like all these files just bunched together with no real explanation of what each file is and does. I'm deleting this and forgetting this junk ever existed! Terrible program! trying to make things easier but in the process breaks the game!

**Comment by Lisias** [comment]
The user is lost on the Module Manager mess that this fork tries to fix.

It's suicidal to have aditional copies of Module Manager on KSP >= 1.8, as the OLDEST ONE is used instead, and not the newest. The ModuleManagerWatchDog is intended to prevent exactly that - but since the user choose to complain about the safety measures that would keep this KSP installment safe, there's nothing more this tool can do about.

This user didn't understood at all the meaning of this fork and its tools, and the best line of action is, indeed, refrain himself of downlading add'ons himself.
